### ISSUE TITLE
Observe Revisionable for different events

### ISSUE THREAD

**Issue by stevebauman** [VentureCraft/revisionable#108]
First of all, just wanted to say thanks a million for this package, and all your hard work. It's amazing!

I just wanted to know, is there a way to use a Laravel Observer to observe created/saved events?

I'm working on a notifications system for my project, and it'd be awesome to observe the one revisions database table for changes and notify a user of the change.

Unfortunately since I'm using the new trait based implementation, I can't capture the events from the trait, unless I'm missing something of course.

Is this possible at all? Thanks again!

EDIT: Just some more details. Since revision checks for changes in each field already, I would prefer to not have to duplicate that functionality for my own observer and check for changes on each field and then send a notification out.

**Comment by astierler** [comment]
Better late than never.. this was released in 1.28.0 :)

**Comment by koichirose** [comment]
Sorry if I bring this up again. I wanted to add some columns to the revisions table (specifically, an IP address), so I thought to use Laravel's model events (observers), but I noticed that RevisionableTrait is simply performing an insert() so no model events are fired.

I can't listen to the events mentioned here ('revisionable.saved') and perform an additional query (update) to add the IP address either, since I'd need the saved revision's ID to perform an update on that row.

Changing this: https://github.com/VentureCraft/revisionable/blob/master/src/Venturecraft/Revisionable/RevisionableTrait.php#L198 to a foreach and using the standard $revision->save() method would fix everything and I could use observers, but I guess the insert() was chosen because it would execute a single query instead of one per change?

What other options are there to add custom data to a revision?
