### ISSUE TITLE
Can Laravel Revisionable track changes by foreign key not primary key?

### ISSUE THREAD

**Issue by KamilFo** [VentureCraft/revisionable#157]
I have a shop database.

Two tables: order and order_products. I want to track changes in order_products and watch it through Order model.

When I update order it overrides all related to this order rows in order_products table so there are always new primary keys so we cant track changes by default. I need to track it via foreign key which is order_id in order table.

So how I should solve this problem?

**Comment by duellsy** [comment]
Revisionable works based on the events that are thrown by the model, create / update / delete, since it seems like in your case you're always creating a new row, rather than modifying an existing one, I'm not sure there's a way around this (apart from changing the way your app saves it's updates to be updates, not creates)
