### ISSUE TITLE
Encrypted Values always marked as 'Changed'

### ISSUE THREAD

**Issue by darraghmckay** [VentureCraft/revisionable#208]
I just implemented this so maybe I'm doing it wrong. 

I'm encrypting most of my values when storing them to the DB so when I 'update' my model revisionable says that all of the fields have been changed and Revisionable history only shows the encrypted values (for old and new) as opposed to the decrypted values.

**Comment by juanvillegas** [comment]
When and how are you doing the encryption? If the encryption is done after revisionable executes, then obviously revisionable will pick up the unencrypted value compare it with the current one (encrypted) and detect it as a change..

**Comment by astierler** [comment]
@darraghmckay it sounds like you are always re-encrypting the values?  I'm not familiar with what you're doing, but it sounds like you're process is re-encrypting the values, and since they are salted, they will always change.

Also, by design, if you are storing data in the database and you want it encrypted, I'd expect you would not want to store the unencrypted values in the revision history?
